language: node_js
os: osx
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
    - "$HOME/.wine"
before_install:
  - brew install wine
  - export PATH="$HOME/.wine:$PATH"
install:
  - cd ./LOMS
  - npm install