
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc3eef7a3a4b216fd1c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
language: node_js
os: osx
node_js:
  - "9"
install:
  - cd ./LOMS
  - npm install

  - cd ../LOMS-Server
  - npm install
before_script:
  - cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=cf8d5db98b9c576e25427d1cc6b19fb0aabb3eeeaad6cf2bc400aed10bfe14bb

  - cd ./LOMS
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=cf8d5db98b9c576e25427d1cc6b19fb0aabb3eeeaad6cf2bc400aed10bfe14bb

  - cd ../LOMS-Server
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=cf8d5db98b9c576e25427d1cc6b19fb0aabb3eeeaad6cf2bc400aed10bfe14bb

script:
  - cd ../LOMS
  - cd ../LOMS-Server


after_script:
  - cd ../LOMS
  - npm install --save-dev istanbul@1.1.0-alpha.1
  - npm install --save-dev mocha-lcov-reporter
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R mocha-lcov-reporter --compilers js:babel-register
  - ./cc-test-reporter format-coverage --output ../coverage/codeclimate.client.json

  - cd ../LOMS-Server
  - npm install --save-dev istanbul@1.1.0-alpha.1
  - npm install --save-dev mocha-lcov-reporter
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R mocha-lcov-reporter --compilers js:babel-register
  - ./cc-test-reporter format-coverage --output ../coverage/codeclimate.server.json

  - cd ..
  - ./cc-test-reporter sum-coverage --parts=2 coverage/codeclimate.client.json coverage/codeclimate.server.json
  - ./cc-test-reporter upload-coverage
cache:
  directories:
    - "LOMS/node_modules"
    - "LOMS-Server/node_modules"