notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc3eef7a3a4b216fd1c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
language: node_js
os: osx
node_js:
  - "6"
install:
  - cd ./LOMS
  - npm install
  - npm run dist-mac
after_script:
  - npm install --save-dev istanbul@1.1.0-alpha.1
  - npm install --save-dev codecov
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R spec --compilers js:babel-register
  - ./node_modules/.bin/codecov
cache:
  directories:
    - "LOMS/node_modules"