language: node_js
os: osx
node_js:
  - "10"
install:
  - npm install
  - npm run build-prod

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=b93754d61350b44f04aa8b6de4ef126a31f87f09a41bd30bb2725705de589c89

script:
  - npm run unit-testing && npm run flow check && npm run lint

after_script:
  - npm install mocha-lcov-reporter@1.3.0
  - npm install istanbul@1.1.0-alpha.1
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R mocha-lcov-reporter --require @babel/register
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - "./node_modules"
