notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc3eef7a3a4b216fd1c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
language: node_js
os: osx
node_js:
  - "10"
install:
  - npm install
  - npm run build-mac

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=cf8d5db98b9c576e25427d1cc6b19fb0aabb3eeeaad6cf2bc400aed10bfe14bb

script:
  - npm run flow && npm run lint

after_script:
  - npm install mocha-lcov-reporter
  - npm install istanbul@1.1.0-alpha.1
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R mocha-lcov-reporter --compilers js:babel-register
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - "./node_modules"
