# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: 10
    
platform: x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node -v
  - npm -v
  # install modules
  - npm install
  - npm run build-prod

# Post-install test scripts.
test_script:
  - npm run flow check && npm run lint

after_test:
  - npm install istanbul@1.1.0-alpha.1
  - npm install codecov@3.0.4
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R spec --require @babel/register
  - ./node_modules/.bin/codecov

cache:
  - node_modules -> package.json

# Don't actually build.
build: off
