# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/1857811ea920596b1bea
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
before_build:
  - npm install -g istanbul
  - npm install -g codecov

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 6.11.0 x64
  # install modules
  - cd ./LOMS
  - npm install
  - npm run dist-win

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
after_test:
  - istanbul cover node_modules\jasmine\bin\jasmine.js

# Don't actually build.
build: off